server:
  port: 8091

ltzf:
  sdk:
    config:
      enabled: true
      app_id: 1104268
      merchant_id: 1673424392
      partner_key: 6d3e889f359fcb83d150e9553a9217b9

# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml